#!/usr/bin/env zsh
set -eu

file=$1
filename=$(basename $file)
executable="${filename%.*}"
extension="${filename##*.}"
echo $file

tempfile="$(mktemp /tmp/${filename}.XXXXXX)"
trap 'rm -rf -- "${tempfile}"' EXIT

if [[ ${extension} == "cpp" ]]; then
  g++ -std=c++17 -Wall -Wextra -Wshadow -O2 ${file} -o ${tempfile} && ${tempfile}
else
  echo "Filetype is not supported"
  exit 1
fi
echo "----------------------------"


