export PATH=$HOME/.local/bin:/usr/local/bin:$PATH

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git fzf-tab zsh-syntax-highlighting zsh-autosuggestions)

# FZF
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

source ~/dotfiles/docker.zsh
source ~/dotfiles/tmux.zsh
source ~/dotfiles/utils.zsh

export TERM=xterm-256color
